<a href="https://colab.research.google.com/github/Muneswar9966/LAB-EXPS/blob/main/EXP_1_Dimensions_Creating_and_Manipulating_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
primes = tf.constant([1, 2, 4, 6, 8, 23], dtype=tf.int32)
print("primes:", primes)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = primes + twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6],[1,4,5]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
primes: tf.Tensor([ 1  2  4  6  8 23], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 2  3  5  7  9 24], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 3  4  6  8 10 25], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [1 4 5]], shape=(3, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]
 [1 4 5]]
